import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {GraphQLClient,gql}from 'graphql-request'
import {useEffect, useState} from 'react'
import PostItem from '../components/PostItem'


const graphqlcms = new GraphQLClient(
  "https://api-eu-central-1.hygraph.com/v2/cl6nnawkm030501tbb3qkexao/master"
);


const QERY = gql`
  {
    posts {
      id
      title
      slug
      description

      text2 {
        html
      }
      date_published
      author {
        id
        name
        avatar {
          url
        }
      }
      coverFoto {
        id
        publishedAt
        url
      }
    }
  }
`;


export async function getStaticProps() {

  const { posts } = await graphqlcms.request(QERY);

  return {
    props: {
      posts,
    },
  };
}

export default function Home({posts}) {
  // const [posts,setPosts] = useState([])

  // useEffect(()=>{

  // },[])
  console.log(posts)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
{
  posts.map(item=><PostItem key={item.id} item={item} />)
}
    </div>
  )
}



